title: Sam Hayes # your name (or website title) here
logo: "/images/profileround.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Spatial data scientist in the energy industry
  <br><br>
  
  <a href="https://www.linkedin.com/in/samantha-hayes-424559158/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

